### ISSUE TITLE
[Dev] Clinical Annotation Module 

### ISSUE THREAD

**Issue by jinxin-wang** [jinxin-wang/Genome_Sequencing_Analysis#13]
1. CNA annotation subworkflow from Yoann's [pipeline](https://github.com/gustaveroussy/MetaPRISM_WES_Pipeline/tree/master/workflow)

https://github.com/jinxin-wang/Genome_Sequencing_Analysis/blob/58718befe578c2f1317e404bd6eb5c92451930ec/workflow/rules/Facets/cnvFacets.smk#LL8C16-L8C25

1. mutation annotation subworkflow from Yoann's [pipeline](https://github.com/gustaveroussy/MetaPRISM_WES_Pipeline/tree/master/workflow)

https://github.com/jinxin-wang/Genome_Sequencing_Analysis/blob/58718befe578c2f1317e404bd6eb5c92451930ec/workflow/rules/Mutect2/Std/mutect2.smk#LL114C30-L114C92

**Comment by tdayris** [comment]
Current state of the branch:

* Dry-run : ok
* DAG : ok
* Exact same command line as MetaPrism: ok
* Exact same scripts as MetaPrism: ok
* Exact same annotations as MetaPrism: ok
* Exace same filters as MetaPrism: to be checked

Tests: on going.
