### ISSUE TITLE
[Bug] Issue with references for BWA alignment

### ISSUE THREAD

**Issue by jsangalang** [jinxin-wang/Genome_Sequencing_Analysis#19]
There seems to be a missing reference file when aligning with BWA. There is no file `/mnt/beegfs/scratch/Lg_PANUNZI/Konstantin/gatk/human_g1k_v37.fasta.bwt.2bit.64` in this directory. Does it need to be indexed again @jinxin-wang , or is it somewhere else?

```
rule bwa_map:
    input: DNA_samples_clean/V100_1.fastq.gz, DNA_samples_clean/V100_2.fastq.gz
    output: bam/V100.bam
    log: logs/bam/V100.bam.log
    jobid: 0
    wildcards: sample=V100
    threads: 32
    resources: mem_mb=102400

Looking to launch executable "/mnt/beegfs/software/bwa/2.2.1/bin/bwa-mem2.avx2", simd = .avx2
Launching executable "/mnt/beegfs/software/bwa/2.2.1/bin/bwa-mem2.avx2"
-----------------------------
Executing in AVX2 mode!!
-----------------------------
* SA compression enabled with xfactor: 8
* Ref file: /mnt/beegfs/scratch/Lg_PANUNZI/Konstantin/gatk/human_g1k_v37.fasta
* Entering FMI_search
ERROR! Unable to open the file: /mnt/beegfs/scratch/Lg_PANUNZI/Konstantin/gatk/human_g1k_v37.fasta.bwt.2bit.64
[Tue Jun  6 20:28:53 2023]
Error in rule bwa_map:
    jobid: 0
    output: bam/V100.bam
    log: logs/bam/V100.bam.log (check log file(s) for error message)
    shell:
        /mnt/beegfs/software/bwa/2.2.1/bin/bwa-mem2 mem -M -R "@RG\tID:bwa\tSM:V100\tPL:ILLUMINA\tLB:truseq" -t 32 /mnt/beegfs/scratch/Lg_PANUNZI/Konstantin/gatk/human_g1k_v37.fasta DNA_samples_clean/V100_1.fastq.gz DNA_samples_clean/V100_2.fastq.gz | ~/.conda/envs/pipeline_GATK_2.1.4_V2/bin/samtools view -bS - | ~/.conda/envs/pipeline_GATK_2.1.4_V2/bin/samtools sort -@ 32 - -o bam/V100.bam 2> logs/bam/V100.bam.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

```

**Comment by jinxin-wang** [comment]
Hello Jomar, @jsangalang 

The error message is : 
ERROR! Unable to open the file: /mnt/beegfs/scratch/Lg_PANUNZI/Konstantin/gatk/human_g1k_v37.fasta.bwt.2bit.64

Could you check if the genome reference is still accessible

**Comment by jsangalang** [comment]
Hi Jinxin @jinxin-wang,
Yes, exactly. The reference `human_g1k_v37.fasta` is accessible in the directory, but the index `human_g1k_v37.fasta.bwt.2bit.64` is not there.

**Comment by jinxin-wang** [comment]
I see, could you help to rebuild the index, plz? Thanks a lot

**Comment by jsangalang** [comment]
Yes, I've indexed it in my scratch, but I don't have writing permissions in the folder where the reference is located.
Could you copy into the directory? 
The re-indexed files are here: `/mnt/beegfs/scratch/j_sangalang/WES_results/ref/`

**Comment by jinxin-wang** [comment]
Okay, it has been copied.

**Comment by jsangalang** [comment]
Thank you!
Could you also copy `human_g1k_v37.fasta.0123` into the directory? It is also needed for BWA. Thank you!

**Comment by jinxin-wang** [comment]
okay, it is done

**Comment by jsangalang** [comment]
Great, thank you!

**Comment by jsangalang** [comment]
I think an even more permanent solution is to move the genome references to /mnt/beegfs/database/bioinfo/

**Comment by jinxin-wang** [comment]
You are right. I will check if I can move them to the database directory

**Comment by jinxin-wang** [comment]
continue with #24
