### ISSUE TITLE
Issue with conda pkgs/free

### ISSUE THREAD

**Issue by jsangalang** [jinxin-wang/Genome_Sequencing_Analysis#9]
From the conda configuration file for creating the environment, some packages are from the /pkgs/free channel which was a channel within defaults prior to conda 4.7. 

```
(base) [j_sangalang@n02 envs]$ conda env create -f META_PRISM_conda_env.txt -n META_PRISM
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: pkgs/free
  channel url: https://conda.anaconda.org/pkgs/free
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

I will see if I can restore the free channel into defaults.

**Comment by jinxin-wang** [comment]
Okay

(base) [j_wang@flamingo-lg-01 ~]$ conda activate meta_prism
(meta_prism) [j_wang@flamingo-lg-01 ~]$ conda config --show channels
channels:
  - defaults
